---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jangomart
  region: us-west-2
  version: "1.21"

managedNodeGroups:
  - name: managedprimary
    desiredCapacity: 3
    instanceType: t3.small
    ssh:
      enableSsm: true

# To enable all of the control plane logs, uncomment below:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:us-west-2:849514089141:key/d9752f5c-bb41-4683-96dc-dae40258d12a
