replicaCount: 1

image:
  repository: maven-helm-postgres
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  # type: NodePort
  type: LoadBalancer
  targetPort: 5000
  port: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
